### ISSUE TITLE
Error installing plugin on QGIS 2.1

### ISSUE THREAD

**Issue by billgeo** [linz/QGIS-AIMS-Plugin#132]
Got 0.8.2 version of plugin from here http://<dev_server>:8080/quercus-4.0.39/plugin_xml.php

When installing my linux version of QGIS 2.1 I get the error below. 

Whats the recommended version of QGIS as a temp workaround?

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 219, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/bmnelson/.qgis2/python/plugins/aims/**init**.py", line 15, in classFactory
    from Plugin import Plugin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/Plugin.py", line 11, in 
    from AimsUI.AimsClient.Gui.Controller import Controller
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/AimsUI/AimsClient/Gui/Controller.py", line 15, in 
    from AIMSDataManager.DataManager import DataManager
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/AIMSDataManager/DataManager.py", line 20, in 
    from DataSync import DataSync,DataSyncFeatures,DataSyncFeeds,DataSyncAdmin
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/AIMSDataManager/DataSync.py", line 24, in 
    from DataUpdater import DataUpdater,DataUpdaterAction,DataUpdaterApproval,DataUpdaterGroupAction,DataUpdaterGroupApproval,DataUpdaterUserAction
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/AIMSDataManager/DataUpdater.py", line 21, in 
    from AimsApi import AimsApi
  File "/usr/lib/python2.7/dist-packages/qgis/utils.py", line 478, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/bmnelson/.qgis2/python/plugins/aims/AIMSDataManager/AimsApi.py", line 18, in 
    from AimsUtility import FeatureType,ActionType,ApprovalType,GroupActionType,GroupApprovalType,UserActionType,FeedType,LogWrap
ImportError: cannot import name UserActionType

**Comment by ghost** [comment]
This looks like it might be an older version of the plugin. UserActionType is a placeholder enumeration for when we implement a User Admin interface. It exists in newer versions of the AimsUtility module but maybe not in the plugin repo on dev?

**Comment by billgeo** [comment]
@SPlanzer as discussed please update README and plugin repository setting to reflect which version of QGIS is needed. 2.8+?

**Comment by SPlanzer** [comment]
read me updated to indicate QGIS 2.6+ is required
