### ISSUE TITLE
Python error when accepting address

### ISSUE THREAD

**Issue by jason-bedford** [linz/QGIS-AIMS-Plugin#231]
I frequently get the error message shown below when accepting an edit from the Review queue.
I'm not sure if this error has been raised previously, so I'm raising it just in case.

====================================================

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "C:/Users/jbedford/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 433, in accept
    self.reviewResolution('accept')
  File "C:/Users/jbedford/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ReviewQueueWidget.py", line 417, in reviewResolution
    if self._controller.RespHandler.handleResp(respId, feedType, action):
  File "C:\Users\jbedford\.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 158, in handleResp
    if self.matchResp(resp, respId, feedType, i, action):
  File "C:\Users\jbedford\.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 139, in matchResp
    self.updateData(resp, feedType, action)
  File "C:\Users\jbedford\.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\ResponseHandler.py", line 56, in updateData
    self.uidm.updateGdata(respObj)
  File "C:\Users\jbedford\.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 235, in updateGdata
    self.data[FEEDS['GR']][groupKey][respFeature._changeId] = respFeature
KeyError: None

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['G:/QGIS 2.8/apps/qgis-ltr/./python/plugins\\processing', 'C:\\Users\\jbedford\\.qgis2\\python\\plugins\\aims', 'G:/QGIS 2.8/apps/qgis-ltr/./python', u'C:/Users/jbedford/.qgis2/python', u'C:/Users/jbedford/.qgis2/python/plugins', 'G:/QGIS 2.8/apps/qgis-ltr/./python/plugins', 'G:\\QGIS 2.8\\bin\\python27.zip', 'G:\\QGIS 2.8\\apps\\Python27\\DLLs', 'G:\\QGIS 2.8\\apps\\Python27\\lib', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\plat-win', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\lib-tk', 'G:\\QGIS 2.8\\bin', 'G:\\QGIS 2.8\\apps\\Python27', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\PIL', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\jinja2-2.7.2-py2.7.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\markupsafe-0.23-py2.7-win32.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\python_dateutil-2.2-py2.7.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\pytz-2014.2-py2.7.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\win32', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\win32\\lib', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\Pythonwin', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\Shapely-1.2.18-py2.7-win32.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\six-1.10.0-py2.7.egg', 'G:\\QGIS 2.8\\apps\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode', u'C:/Users/jbedford/.qgis2//python', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '..', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'C:\\Users\\jbedford\\.qgis2\\python\\plugins\\intramaps_qgis\\ui', 'G:\\QGIS 2.8\\apps\\qgis-ltr\\python\\plugins\\fTools\\tools', '.qgis2/python/plugins/QGIS-AIMS-Plugin', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
Thanks @jason-bedford for opening this. I am not aware of it and there is no records in the github issues either. 

If you come to understand the set of circumstances leading to this can you document steps to reproduce it. 

Can you also add any information that might inform the priority of resolving the bug
* What happens after you close the traceback report? 
  * Does the system crash?
  * Is the UI out of sync with the API
  * Can you continue to use the UI?

**Comment by jason-bedford** [comment]
The system does not crash, and I can continue to use the UI. 
The address remains in the Review queue, and clicking Accept a second time on the same address tells me that another user has edited the feature (or whatever the standard message says).
After a while the address becomes accepted and disappears from the Review queue.
It's possible that the UI is out of sync with the API, but not sure how to test this.

**Comment by SPlanzer** [comment]
@jason-bedford Is this still an issue?

**Comment by jason-bedford** [comment]
@SPlanzer Yes I believe it is still an issue. I'm still getting an error on occasion so assume it is the same one.
It seems to happen after I've edited an existing address. It will remain in the queue but if I then Accept a new address from the queue it will then clear itself.

**Comment by SPlanzer** [comment]
cheers @jason-bedford. Im doing an issue tidy up, I wont be assigned this as a priority anytime in the near future. For this reason I will take myself of and assign @YingtingChen and leave it up to the addressing team to prioritise
