### ISSUE TITLE
Submit Address - Address mandatory

### ISSUE THREAD

**Issue by Deb-Jones** [linz/QGIS-AIMS-Plugin#47]
When I submit an address with only a road, I get a python error.

An error has occurred while executing Python code:

Traceback (most recent call last):
  File "D:/Users/djjones/.qgis2/python/plugins\aims\AimsUI\AimsClient\Gui\ChangeQueueWidget.py", line 119, in submitAddress
    self._controller.uidm.addAddress(self.feature, respId)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AimsUI\AimsClient\Gui\UiDataManager.py", line 129, in addAddress
    self.dm.addAddress(feature, respId)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 201, in addAddress
    self._addressAction(address,ActionType.ADD,reqid)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 212, in _addressAction
    self._queueAction(FeedRef((FeatureType.ADDRESS,FeedType.CHANGEFEED)), at, address)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataManager.py", line 272, in _queueAction
    self.notify(feedref)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\Observable.py", line 30, in notify
    observer.observe(_args, *_kwargs)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 79, in observe
    self.client.processInputQueue(changelist)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 353, in processInputQueue
    duref = self.processFeature(at,feature)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataSync.py", line 363, in processFeature
    self.duinst[ref].setup(self.etft,at,feature)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\DataUpdater.py", line 252, in setup
    self.payload = self.afactory.convertAddress(self.agobj,self.at)
  File "D:\Users\djjones.qgis2\python\plugins\aims\AIMSDataManager\AddressFactory.py", line 117, in convertAddress
    raise AddressConversionException(msg)
AddressConversionException

Python version:
2.7.4 (default, Apr  6 2013, 19:54:46) [MSC v.1500 32 bit (Intel)]

QGIS version:
2.8.7-Wien Wien, 8a47921

Python path: ['D:/Users/djjones/.qgis2/python/plugins\processing', 'D:\Users\djjones\.qgis2\python\plugins\aims', 'G:/QGIS28/apps/qgis-ltr/./python', u'D:/Users/djjones/.qgis2/python', u'D:/Users/djjones/.qgis2/python/plugins', 'G:/QGIS28/apps/qgis-ltr/./python/plugins', 'C:\Program Files (x86)\ArcGIS\bin', 'G:\QGIS28\bin\python27.zip', 'G:\QGIS28\apps\Python27\DLLs', 'G:\QGIS28\apps\Python27\lib', 'G:\QGIS28\apps\Python27\lib\plat-win', 'G:\QGIS28\apps\Python27\lib\lib-tk', 'G:\QGIS28\bin', 'G:\QGIS28\apps\Python27', 'G:\QGIS28\apps\Python27\lib\site-packages', 'G:\QGIS28\apps\Python27\lib\site-packages\PIL', 'G:\QGIS28\apps\Python27\lib\site-packages\jinja2-2.7.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\markupsafe-0.23-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\python_dateutil-2.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\pytz-2014.2-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\win32', 'G:\QGIS28\apps\Python27\lib\site-packages\win32\lib', 'G:\QGIS28\apps\Python27\lib\site-packages\Pythonwin', 'G:\QGIS28\apps\Python27\lib\site-packages\Shapely-1.2.18-py2.7-win32.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\six-1.10.0-py2.7.egg', 'G:\QGIS28\apps\Python27\lib\site-packages\wx-2.8-msw-unicode', u'D:/Users/djjones/.qgis2//python', '..', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc', 'G:\QGIS28\apps\qgis-ltr\python\plugins\ElectoralAddressPlugin', 'G:\QGIS28\apps\qgis-ltr\python\plugins\fTools\tools', 'D:\Users\djjones\.qgis2\python\plugins\intramaps_qgis\ui', '.qgis2/python/plugins/AIMS_Plugin_threaded', '/opt/eclipse/plugins/org.python.pydev_4.4.0.201510052309/pysrc']

**Comment by SPlanzer** [comment]
Please retest in 0.8.1

It should now be expected that a error message is raised to the user at which point the user can add further address information.

**Comment by Deb-Jones** [comment]
Tested 0.8.1
Error pop up stating Please supply a Complete Address Number.
Selected OK, entered a number and was able to submit the add.
